const baseBlown = 
`
AAAAAAAAAAAAAIIIIIIIII==================================================================================================
AAAAAAAAAAAIIIIIIIIII===================================================================================================
AAAAAAAAAAIIIIIIIIIII=========================================================..========================================
AAAAAAAAAIIIIIIIIIIII=======================================================.......=====================================
AAAAAAAIIIIIIIIIIIIIII============================================IIIIIIIII=.........===================================
AAAAAAAIIIIIIIIIIIIIIIII=======================================IIIIIIIIIIII=........====================================
AAAAAAAIIIIIIIIIIIIIIIIIIIII=================================IIIIIIIIIIIIIII==...==IIII=================================
AAAAAAAAAIIIIIIIIIIIIIIIIIIIIII============================IIIIIIIIIIIIIIIIII===IIIIIIIII===II==========================
AAAAAAAAAAAIIIIIIIIIIIIIIIIIIIIIIII======================IIIIIIIIIIIIIIIIIIIIIXIIIIIIIIIIIAXMMMAAI========II============
AAAAAAAAAAAAAIIIIIIIIIIIIIIIIIIIIIIIIIIII==============IIIIIIIIIIIIIIIIIIIIIIIAIIIIIIIIIIIXWMWWWWXA===IIAMXI============
AAAAAAAAAAAAAAAAAIIIIIIIIIIIIIIIIIIIIIIIIIIII=====IIIIIIIIIIIIIIIIIIIIIIIIIIIIAIIIIIIIIIIXXMMMWWWWMXMMXXAI==============
AAAAAAAAAAAAAAAAAAAAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII==IIAAAAIIIIAXXMXXMMWWWXAAXXXI==============
AAAAAAAAAAAAAAAAAAAAAAAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXAAAAXXMWWWWWWWWWWMXAXXAAAA===================
XAAAAAAAAAAAAAMMMMMMMMMMMXAAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIAXXWWWMMWWWWWWWWWWMMMMMMXAX===================
XXXXAAAAAAAAAAWWWWWWWWWWWWWAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIAAXAAIIIIIIXAXMMWWWWWWWWWWWWWWMMMMMMMX===================
XXXXXXXXXXXXAXWWWWWWWWWWWWWAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIAXWMWWWMMXXAIMMXWWWMMMWWWWWWWWWWWWWWWMMX===================
XXXXXXXXXXXXXXWWWWWWWWWWWWWAAAAAAAIIIIIIIIIIIIIIIIIIIIIIIIIIAXWWWWWWWWWWWMMMXWWWWWMMMWWWWMWWWMMMMMMXX===================
XXXXXXXXXXXXXXWWWWWWWWWWWWWAAAAAAAAAAAIIIIIIIIIIIIIIIIIIIIIIMWWWWWWWWWWWWWWWXWWWWWMAAXWWWWWWWWMMMMMXX===================
XXXXXXXXXXXXXXWWWWWWWWWWWWWXAAAAAAAAAAAAAAIIIIIIIIIIIIIIIIIMWWWWWWXAMWWWWWWWXWWWWWWWWWWWWWWWWWWWWMMXX===================
XXXXXXXXXXXXMXWWWWWWWWWWWWWXAAAAAAAAAAAAAAAAAIIIIIIIIIIIIIMWWWWWWWIIIIIXMMMMXMMMXXMWWWWWWWWWWWWWWWWMXI==================
AAAAAAAAAAAAXXWWWWWWWWWWWWWAAAAAIIIIIIIIIIIIIIIIIIIIIIIIIMWWWWWWWAIIII=IWWWWWWWWWWWWWWWWWWWWWWWWWWWMX===================
AAAAAAAAAAAXXMWWWWWWWWWWWWWAAAAAAAAAAAAAAAAAAAAAAAIIIIIIMWWWWWWWMIIIIIIAWWWWWWWWWWWWWWWWWWWWWWWWWWMXAAIIIIIIIIIIIIII====
IIIIIIIIIIIIIXWWWWWWWWWWWWWIIIIIIIIIIIIIIII===========AMWWWWWWWW=======IWWWWWWWWWWWWWWWWWWWWWWMMWWMMXII==============...
AAAAAAAAAAXXXXWWWWWWWWWWWWWIIIIIIIIIIIIIIIII======IIIAMWWWWWWI=========IWWWWWWWWWWWWWMMMMMMXXXXXXAMXAAIIIIIIIIIIIIIII===
IIIAAAXXXXXXXXXXXXXXXXXXXAI=======================IAAAAAAAAXXAAAAAAAAAAAWWWWWWWWWWWWWWWWWWWWWWWWMMMMXXXXXXXXXXAAAAIIII==
IIIIIIIIIIIIIII=========================================IIII============AAAAAAAAAAAAIII==============================...
IIIIIIIIIIIIIIII==================================IIIIIIIII=====IIII=================================================...
`

export const BlownAway = baseBlown