const tree = `
                                                                     =I.==.......=======================================
========================================================............=AXAXAA=.=====..====================================
==================================================.....====.....=IXAAXMMMXXXXXIAIA=I....==.=============================
=================================================..............==AXMMMMMMMMXMMMXXXAI.=IA=II============================.
============================================...............=.=.IAAAMMMMWMMMWMMMMMMXXAXAAIXIAI==========================.
=========================================.==..............=IIMAXXAAXAXMMMMMWWWMMMMXXAIIAXXXA=..========================.
====================================...==.................AIMXMMMXMMMXMMMMMXMWMMWMMMMMMMMMXA=..========================.
====================================.....................=AAAXXXMMMMXMMMMMMMMMMMMMMMWWMMMMXIA=..=======================.
====================================.......................IIAAXXXXMMMMMMMMMMWMMMWWWMMMMMMMMXXII=..====================.
=================================...==......................=AXXXXXXMMXXXAXMMWWMMMMMMMMMXMMMMMAAI..====================.
==============================......=.......................=IIAAAAAAXXXAXMXMMMMMMMWWWMWMWWWMXAAI=..===================.
=================================.........................=II=II=I=IAXMMXXMMXMXMWMMMMWWWMMMMMMXXA=.....================.
===========================.........................===AII=IAAIX=IAIIAAAIIAAXMMXMWXMWWWMMWWWMMMMXAAII...===============.
======================..............................=IXMXAXXXMXXXMMXAAXXIIAMAAMMMMMWWMMMMWWMMMWWMMXAA=.....============.
====================...==............................=IAXXXXXMXMXMMMMMMMMMMMXXMMMWWMMXMMWMWMMXMMMMXXXA==......=========.
====================..=====...........................==AIIAIXXMMMMMXMXAAXMMWMMMMWMXXAXMMXMMMMMXMMXXAAI=......=========.
===================.....................................==.=AAMMXXMMMMMMXMMMMMMWWWWMMMXAAMMMMMAXXXAAAI.........========.
===================....=.................................====IAXMMMMMMMMXMAXAMMMWWWMMMMMMMMMMMMXAXMMAI........=========.
===================.......................................I==IIAXXXMXMMMMXMMMMXXXMMMMMMMMMMMXMMMMMXAI=..........=======.
==================........................................AAMXXMMMMMMMMMMMMMMMMMMMMMXAMMMXMMMXMMXMXAA=...........======.
===================.......................................=AAXMXMMMMMMMXXMMMXMMMMMWMXIMXXXXAAAAAAAII..........=========.
===================.....................................==IIMXXMXMMMMMWMMMXMMMMMMMMMMMXXAAXXXAI=IA==............=======.
=================....==..............................==I=I=XXXXXXMXMMMMXMAMXXMMMMMMMXMXMMMMMMXMMMXXA=I=I..........===...
=================..==................................IIAXIAXAAAAXXXXXXAAAIAXXMXMMMMMMMMMMXMMMMMMMMMMXXI=........=.......
=================...................................IAAXAXAIIAI=IAAI==.=IAIXMMMMMMMMMMXXIXMMMMMMMMMMXAA=................
=================....................................==IIAXXI==..=I=.IAMMMWWMMAAMMMMXXMMMMMMMMMMMMMMMMMXI=..............
=================.......................................=I======IAXXXXMMMMWMMMXXMMMMMMWMXXXMMMMMMMMMMMXAA=..............
==============..............................................=AXMMMMMMMMMMMMWMMMMXMMMMMMXMMMMMXMMMMMMMMMMAI==............
================...=====.....................................IAXXMMMMMMMMMMMMMMXAMMMMMXMMMMMMMXXXXXMMMXAII==............
=====================....=................................==IIIXXXMMMXMMXXXXXXMMMWMMMMMMMMMMMMMX=AAXAAI=................
===================........................................IIIIAAXXAAXAXXMMAAAXMXMWMMMXMMMMMMMMXIIII=.=.................
===================.......................................==AAXAAAAA===AXAIAXXMXXMMMMMMMMXXXMMMMMMXAIIAI=...............
===================.................................=.IA.I=IIIIXXAAMMMXXXMMAAAXAAMMMMMMXXMMXXMMMMMMMMXXA................
===================...............................=IAXAXAAIXXMMMMXMMMMMXXMMXXMMMMMMMMMMMMMXMMMMXMMMMXXIII...............
===================...............................=IIAXXXAXXAXXMMXXXAIAXIAMMXXMMMMMMMMMMMAXXXXMXXXAI...=................
==================.....===...........................==IIAI=..===.==IIAAMMMMMMMAXWMMMMMMMMMMXAAXAI=.....................
====================.....=.......................................==..=AIXMXMMXXXXMMMMMMMMMMAI=III==IAI=..=..............
======================....==.................................=AIAXXXMXMMMMMXXXXXXMMMMMXIXXMMXMMMXMMXMAAXAI..............
========================...................................=IIIAXXXXXXXXXIIIIIIIIAMMMMXAXXMMXXMMMMMMMMMXA==.............
============================............................==AAXIXXXXAAXAIIAAAAAXXXXMMMMMMXAXXXXMMXXMMMAXAXXI=.............
==============================.......................===IIXAXXMXMMI=A=IAIIXIAXIIXMMMMMMI==AXXAXXAAXIAXXXAAAA............
===============================....................=IAAXAXXXXXMMMMXXXMMWMWMWMMMXXMMMMMM==XMMMMXAAAAXXAAMXAI=............
================================....................IIAAAXXXXXXXXXXAXMMWWMMXXXMXXMMMMXMMMMMMWMMXXXXXMMMXAAA=............
================================.....................==.=IAAII=IIIIIXMXXXAIIIXAMMMMMMMXMMMMMMMMMMXXXAAXMMAXIII..........
===================================...==......................==.===IIAIAAAXXXXMMMMMMMMXXMMMXXXXXXMXMMMXXXMXAAI=........
=========================================.==......=I.====...=IXXXXMXMMMMXXMMMXXXXMMMMMMXIIIXXAAXXXXXXMXAAXAXMAA==.......
=========================================........=IXAIAXAXMAAXXXXXXXXXXXMMMMMXMMXMMMMMMMMMAXXXXXXXAXXAXXMXXXXMAI=.......
=========================================........=I=AXXMXXXMMMMXAAAIIIIXXXMXMMMXXMMMMMMXXIAXXXMAAXXMAIAXXXXAAIAAA.......
============================================..=.==IAIXXXXXXAAAII==I=A=AAAXXXXXXMMMMXXMMXAAAAI=AAAXIIIIAAAIXAXAII===...=.
============================================..=IAAIXXXXXXAII===.I..I.IAXAAI.=XXIXMMXXMMMAAAXXXI======..=IIAAXIIII==.===.
================================================IAAAIII==I=..=.===I=IXXX=I=AXI==XMMMMMMMIIXXMXXMXAAII=.==..=II===.=====.
===============================================II=====I=I=....==IA=AMXXXMMMMMMXXXXMMMMMMAAXMXXXXMMXXMXIAAIII=.=========.
=================================================..=.====.....I=AXMMXMMMXXMXIAAXXXMMMMMMXI=.IAX=IAXXXXMAXXAAI==========.
===========================================================.=I=IXXXXXXMXXXX==IMXXXMMXXXMAIIAI=XXAAAXXAAAXMXXI==========.
=============================================================IAXXAXXXMXMXXMXAXXXXXXMMXXMXIIAXAIXXIA====IAAAAI==========.
================================================================AXAXMXXXMMMMXMMMXMXXMMMMX.IAXMMXXA=.===================.
===============================================================.=A=II=IAXAXAXXXXIMMMMMMMXIIAXXAXI======================.
================================================================AII===IIAAAXAAXAAMMMMXXMMAAAIIAAA=======================
===============================================================II=========AAXXXXXMMMMMMMXA..=IAXXXA=====================
===============================================================A===I=A====II==IXXMMXMMMMXXAIIII=AAAA====================
==============================================================IIIAXXXXXAIIAIIXXI.XMXMMMXXXMXAAAAXXAI====================
=============================================================IIIAAIII==III==XAA==XMXMMMMX==AI=====I=====================
============================================================II===========IAI==XI=XMXMMXMX===A===========================
============================================================I=======IIXXAI===IAAIXMMMMMXX===X===========================
XAXXXAI===IIII=III===================================================AXXXAAAI=IIAXMMMXMMM===II==========================
XXXXXXA==IAAIAIAAI=I=================================================AAIAAIIAII==XMXXMMMMI====II========================
XXXXXXXIIAAAAAIAAIII=================================================I====IAIIIIIXMMMMMMMA======I=======================
XXXXXXXAAAAAAAAAAAAAIIIIIII=I======I===============================II=====IIIIIIIXMMMMMMMX==============================
XXXXXXXXAAAAAAAAXXXAIIIIIIAIIIIIIIIXII==========================IIII=========AXAIXMMMMMMMA==============================
XXXXXXXXAXXAAXXXXXXXIIIIAXXAIIIIIAXXXII=IIIIIIII=====II=======IIIAIII===IAAIAAXXAXMMMMMMMI===II=IAI===IAII======III==II=
XXXXXXXXXXXXXXXXXXXXAIIAXXXXAXIIAXXXXXIIIIIAIIIIIIIAIIIIIIIIIIIIIIIIAIIIAXXAAAXXXXMMMMMMMAAI=IAIAXAAIIAXAIII=IIIAAIIIAXA
XXXXXXXXXXXXXXXXXXXXAAAXXXXXXXAIXXXXXXAAAIAAIIIIIIAAIIIIIAAIIIIIIIIAAAAAXXXXAXXXXXMMMMMMMXXAAAXAAXXXXAXXXAAAIAIIAAAIXXXA
XXXXXXXXXXXXXXXXXXXXXAXXXXXXXXXAXXXXXXXXAIAAAXAIIAAXAAAIAAAAAIAIIIIAXXXXXXXXXXXXXMMMMMMMMXXXXXXXAXXXXXXXXXXXAXAAAAAAXXXA
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXAXXXXMMXXXXXXXXAIAXXXXXAIAAXAIIAAAAAXXXXXXXXXXXXXXMMMMMMMMXXXXXXXXXXXXXXXXXXXXXXAXXXXXXXA
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXMMXXXXXXXXXXAAXXXXXAAAXMXAAXXXAAXXXXXMXXXXXXXXMMMMMMMXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXA
XXXXXMXXXXXXXXXXXXXXXXXXXXXXXXXXXXXMMMMXXXXXXXXXXXXMMXXXXXXXXXXXXXXAAAXMMMXXXXXXXMMMMMMMMXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXA
AAAXMMXIAAIAAAXXXAAAIAAAAIIAXAIIAIAXXMXAXAAXAAXXXAAXXAXXXXXXAXXXAXXAAAXMMMXAAAAXXMMMMMMMMXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXA
===MMXX=XXIAXXMXMXII==III=IIII=I=AAAAXXAAIIIIIAAXAIAXAAIXXXIIAA==AAAIIXXMXXI===AMMWMMMMMMXIIAIIIIAXMXAIIIIAXAAAXXXXXXAAA
AIAXMXAAAA==IXMXXA==IAI==III====IAAXXXAII====IAAAAXXXAAAXXXAXAAXIAXXXAXXXMXXI==XMWMMMMMMMX========IIII=========IIII====I
XAAXMXAXXX=IAXMMXXI=IIIIAII======IAAAXAXI========IAXXXAAXXXAXAAA=IIIIIIIAXAAI==AXXMWWMMWMMI==================I==IIIIIII=
MXAAAMMMMMI=IAAXXAII==IAXAI=======AXXMAAAAI======IIAAAXXXXXXAAXI=======IAAII==IXMWWWWWWWMMI=====IIIIIIIIIIIIIIIIIIIIIII=
MXXAAXXMMXAI=I==================IIIIIIIII==I=========IIIIIIAAIIIIIIIIIIAXXAAIAAXWWWWWWWWMMA==IIIIIIIIIIIIIIIIIIIIIIIIII=
AIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII=IIIIIAXMMXMXXXAAXXXXXMMMMWWMXXAAAAAAAAAAAAAAAAAIIAAAAAAAI
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII=`

export const PineTree = tree.replaceAll("=", " ").replaceAll(".", " ")